#
# Makefile
#
# Author : Joseph Lin
# E-mail : joseph.lin@aliyun.com
#
###
###
###

MAKE = make

COPY = cp
COPY_FLAGS =  

REMOVE = rm
REMOVE_FLAGS = -f

InstallPath := ../WorkPath/var/www/

.PHONY: all install clean clean_all $(InstallPath)

all: 
	@echo "  nothing need to do here!   \n"


install: 
	$(COPY) $(COPY_FLAGS) ./environment-variables.html $(InstallPath)

clean:
	@echo "  not achived this!   \n"

